spring:
   application:
    name: Requestor-service


server:
  port: 8301


eureka:
 instance:
     prefer-ip-address: true
     instance-id: ${spring.application.name}:${random.value}
 client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/
 
       